Add coverage on project
OmniTrade/client-ruby pull request #19
Opened 2019-01-25 19:15 UTC by ViniciusAlmeidaSilva

![coverage](https://user-images.githubusercontent.com/34649990/51767526-d2926880-20c4-11e9-8e26-e6274fecfbbc.png)

2019-01-27 13:25 UTC, adbatista requested changes

2019-01-27 13:25 UTC, adbatista commented on spec/spec_helper.rb
> +SimpleCov.start
simplecov need to be required before the lib code

2019-01-27 13:25 UTC, adbatista commented on spec/spec_helper.rb
> +SimpleCov.start
https://github.com/colszowka/simplecov#getting-started

> Load and launch SimpleCov at the very top of your test/test_helper.rb (or spec_helper.rb, rails_helper, cucumber env.rb, or whatever your preferred test framework uses):

2019-01-31 18:33 UTC, sobrinho approved these changes

2019-01-31 18:35 UTC, adbatista commented
fix the conflicts pls

2019-01-31 18:58 UTC, davidsilveira approved these changes

2019-01-31 19:20 UTC, davidsilveira approved these changes
Looks good ;)

2019-01-31 20:02 UTC, davidsilveira commented
@ViniciusAlmeidaSilva I have an observation, you could exclude the `'/spec'` folder from this verification. I believe it's unnecessary to verify whether this folder is covered or not.
@sobrinho and @adbatista what do you think about it?

2019-01-31 20:03 UTC, adbatista commented
sure, remove it

2019-02-01 12:06 UTC, adbatista approved these changes

2019-02-01 12:06 UTC, merged

2019-02-01 13:42 UTC, andrerpbts commented
👏